name: Docker Image CI - easy_credit_check

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./challenge/easy_credit_check
      run: docker build . --file Dockerfile --tag credit_check:$(date +%s)