name: Docker Image CI - hard_phoebes_smorgasbord

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./challenge/hard_phoebes_smorgasbord
      run: docker build . --file Dockerfile --tag smorgasbord:$(date +%s)