name: Docker Image CI - medium_rob_vader

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: challenge/medium_rob_vader
      run: docker build . --file Dockerfile --tag vader:$(date +%s)