name: Docker Image CI - medium_honey_i_shrunk_the_pets

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: challenge/medium_honey_i_shrink_the_pets
      run: docker build . --file Dockerfile --tag pets:$(date +%s)