name: Docker Image CI - medium_flying_pig

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./challenge/medium_flying_pig
      run: docker build . --file Dockerfile --tag flying_pig:$(date +%s)