name: Docker Image CI - medium_stonks

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: challenge/medium_stonks
      run: docker build . --file Dockerfile --tag stonks:$(date +%s)