name: Docker Image CI - easy_darth_plagueis

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./challenge/easy_darth_plagueis
      run: docker build . --file Dockerfile --tag darth_plagueis:$(date +%s)